print("Write a Sentence and I'll cpount the letters is the sentence.")
sentence = input()
length = len(sentence)
print(f"Here was your sentence: {sentence} ")
print(f"There are {length} characters in your sentence.")
